### ISSUE TITLE
CMA Cpp ignores x0 / guess

### ISSUE THREAD

**Issue by MLopez-Ibanez** [dietmarwo/fast-cma-es#9]
It seems that CMA Cpp completely ignores x0 /guess as this code shows:

https://github.com/dietmarwo/fast-cma-es/blob/7952d2b70dc76d8f9d3bc326fd19f98fd93e9ff6/_fcmaescpp/acmaesoptimizer.cpp#L163-L165

Since guess is not evaluated, its value is assumed to be DBL_MAX, which means that it gets quickly removed.

What should happen is that `guess` is evaluated in the initialization and `bestValue` updated accordingly. And even better interface would allow to specify `guessValue` since this is often the best solution found in a previous iteration and we may wish to avoid evaluating it again.

**Comment by dietmarwo** [comment]
Your observation is correct. guess is not evaluated.  Not sure what you mean with "specify guessValue".

https://github.com/dietmarwo/fast-cma-es/blob/4b27f00e226bddda9b61492d5509ee34000c7400/fcmaes/cmaescpp.py#L107-L110

shows that you can specify a guess argument vector. 

guess is not evaluated on purpose. The idea is to enhance the chance that the algorithm finds a new better
solution by avoiding the guess being part of the population. You may explicitly evaluate the guess to avoid ending up with a worse solution. Use small input_sigma if you want to explore the "surroundings" of the guess. 

Because of limitations of the Python-C++ interface based on ctypes the interaction with CMA-ES is limited here. 
The Python implementation is more flexible in providing an ask/tell interface
https://github.com/dietmarwo/fast-cma-es/blob/4b27f00e226bddda9b61492d5509ee34000c7400/fcmaes/cmaes.py#L270
where you can supply and argument/value pair you want to avoid unnecessary function calls. The C++ variant is
meant to be used in the context of parallel retry. For expensive objective functions the overhead of Python is not relevant, so the Python CMA-ES can be used instead.
